arch = {
	packages = [
		"alsa-scarlett-gui",
		"breeze-icons",
		"cheat-bin",
		"creality-print-bin",
		"drawio-desktop",
		"fprintd",
		"freecad",
		"handlr-regex",
		"helium-browser-bin",
		"helvum",
		"httpdirfs", # required by ttf-ms-win11-auto
		"keepassxc",
		"lf",
		"mpv",
		"neovim",
		"nextcloud-client",
		"noto-fonts-cjk",
		"noto-fonts-emoji",
		"opensnitch",
		"otf-xkcd-font",
		"piper",
		"plasma-meta",
		"plymouth-kcm",
		"profile-sync-daemon",
		"profile-sync-daemon-thunderbird",
		"profile-sync-daemon-zen",
		"pulsemixer",
		"qt5-wayland",
		"qt5ct",
		"qt6-wayland",
		"speedcrunch",
		"system-config-printer", "python-pysmbc", #optional
		"thunderbird",
		"timewall-bin",
		"torbrowser-launcher",
		"ttf-courier-prime",
		"ttf-fira-mono",
		"ttf-fira-sans",
		"ttf-firacode-nerd",
		"ttf-hack-nerd",
		"ttf-heuristica",
		"ttf-jetbrains-mono-nerd",
		"ttf-ms-win11-auto",
		"ttf-roboto",
		"wavebox",
		"wl-clipboard",
		"xdg-desktop-portal",
		"xorg-server",
		"xorg-xwayland",
		"zathura",
		"zathura-pdf-mupdf",
		"zed", "openbsd-netcat", #optional
		"zen-browser-bin",
	]
}

flatpak = {
	packages = [
		"system:com.github.jeromerobert.pdfarranger",
		"system:de.bund.ausweisapp.ausweisapp2",
		"system:io.missioncenter.MissionCenter",
		"system:org.apache.directory.studio",
		"system:org.fkoehler.KTailctl",
		"system:org.gnome.Maps",
		"system:org.kde.CrowTranslate",
		"system:org.onlyoffice.desktopeditors",
		"system:org.raspberrypi.rpi-imager",
		"system:org.signal.Signal",
	]
}
