arch = {
	packages = [
		"arduino-cli",
		"arm-none-eabi-gcc",
		"arm-none-eabi-newlib",
		"asar",
		"asciidoc",
		"asciidoctor",
		"autoconf",
		"automake",
		"binutils",
		"bison",
		"boost",
		"bpf",
		"cgdb",
		"clang",
		"cmake",
		"dbeaver",
		"delve",
		"docker-buildx",
		"docker-compose",
		"elfutils",
		"esptool",
		"extra-cmake-modules",
		"gcc",
		"gdb-dashboard",
		"git-lfs",
		"gitlab-ci-local",
		"go",
		"goreleaser",
		"highlight",
		"iperf3",
		"ipython",
		"jdk17-openjdk",
		"jq",
		"kotlin",
		"ktlint",
		"lazydocker-bin",
		"lazygit",
		"libtool",
		"lldb",
		"llvm",
		"m4",
		"make",
		"maven",
		"meson",
		"multipath-tools",
		"nasm",
		"nmap",
		"oath-toolkit",
		"opencl-mesa",
		"pyright",
		"python-docker",
		"python-ipykernel",
		"python-matplotlib",
		"python-pip",
		"python-pylint",
		"python-pytest",
		"rustup",
		"scdoc",
		"source-highlight",
		"sqlitebrowser",
		"step-cli",
		"texinfo",
		"texlab",
		"traceroute",
		"typescript",
		"uv",
		"valgrind",
		"vbindiff",
		"virt-viewer",
		"visual-studio-code-bin",
		"wireshark-qt",
		"yarn",
	]
}

flatpak = {
	packages = [
		"io.github.Omniaevo.mqtt5-explorer",
		"es.danirod.Cartero",
	]
}

cargo = {
	packages = [
		"cargo-generate",
		"ravedude",
	]
}
