arch = {
	packages = [
		"gamescope",
		"streamlink-twitch-gui-bin",
		"unigine-heaven",
		"wine",
	]
}

flatpak = {
	packages = [
		"system:com.valvesoftware.Steam",
		"system:org.freedesktop.Platform.VulkanLayer.gamescope",
	]
}

