arch = {
	packages = [
		"ark",
		"audex",
		"colord-kde",
		"filelight",
		"flatpak-kcm",
		"francis",
		"k3b",
		"kalk",
		"kamera",
		"kcharselect",
		"kclock",
		"kcolorchooser",
		"kde-accessibility-meta",
		"kde-system-meta",
		"kdegraphics-thumbnailers",
		"kdenlive",
		"kdialog",
		"kgpg",
		"kio-extras",
		"kio-gdrive",
		"kio-zeroconf",
		"koko",
		"kruler",
		"kteatime",
		"ktimer",
		"kwalletmanager",
		"kweather",
		"kwin-effect-rounded-corners",
		"kwin-effects-better-blur-dx",
		"okular",
		"skanpage",
		"spectacle",
		"svgpart",
	]
}

