arch = {
	packages = [
		"alacritty",
		"android-file-transfer",
		"android-tools",
		"ansible",
		"ansible-lint",
		"broot",
		"carapace-bin",
		"chezmoi",
		"chezmoi_modify_manager",
		"ddrescue",
		"diffpdf",
		"eza",
		"fastfetch",
		"gawk",
		"gzip",
		"harper",
		"heimdall",
		"htop",
		"hwinfo",
		"ldns",
		"lsof",
		"nano",
		"nvme-cli",
		"obsidian",
		"parted",
		"patch",
		"pdfpc",
		"pdftk",
		"perf",
		"perl-rename",
		"plocate",
		"powertop",
		"python-keyring",
		"rbw",
		"rclone",
		"ripgrep",
		"rsync",
		"sed",
		"scarlett2-git",
		"smartmontools",
		"solaar",
		"starship",
		"sysstat",
		"tailscale",
		"tcpdump",
		"time",
		"timeshift",
		"timeshift-autosnap",
		"tk",
		"tmux",
		"translate-shell",
		"ufw",
		"unarchiver",
		"unrar",
		"vi",
		"wego",
		"wget",
		"which",
		"winbox",
		"wireguard-tools",
		"wireless_tools",
		"xorg-xwininfo",
		"zip",
	]
}

